apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "oci-quickcache.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oci-quickcache.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "oci-quickcache.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
