apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oci-quickcache.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oci-quickcache.labels" . | nindent 4 }}
